-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT into friends (name) VALUES ('George');
-- INSERT into friends (name) VALUES ('Lady');
-- INSERT into friends (name) VALUES ('Hajda');
-- INSERT into friends (name) VALUES ('Lenakolokitha');
